# Generated by Django 5.2.3 on 2025-06-29 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.meal'),
        ),
    ]
